/**
 * 业态 / 产线系统预设模板
 * 冲突消解：产线 excludes 优先于业态（选项 A）
 */
import { FEATURE_REGISTRY_L1, type BusinessTypeTag, type FeatureTier } from "./feature-registry";
import type { BusinessTypeTaxonomy } from "./feature-presets-taxonomy";

export interface PresetFeatureEntry {
  featureId: string;
  tier: FeatureTier;
}

export interface BusinessTypePreset {
  id: BusinessTypeTag;
  title: string;
  titleEn: string;
  features: PresetFeatureEntry[];
  version: number;
  /** 引导 Step 1 分组；运营自定义业态可省略 */
  taxonomy?: BusinessTypeTaxonomy;
}

export interface ProductLineQuickBundle {
  id: string;
  title: string;
  titleEn: string;
  presetIds: string[];
}

function f(featureId: string, tier: FeatureTier = "recommended"): PresetFeatureEntry {
  return { featureId, tier };
}

export const BUSINESS_TYPE_PRESETS: BusinessTypePreset[] = [
  {
    id: "fast-food",
    title: "快餐",
    titleEn: "Quick service (QSR)",
    version: 1,
    taxonomy: { group: "service-mode", sortOrder: 1 },
    features: [
      f("store-mgmt", "core"),
      f("dashboard", "core"),
      f("product-center-main", "core"),
      f("transactions", "core"),
      f("orders", "recommended"),
      f("kitchen-kds", "recommended"),
      f("print-templates", "recommended"),
      f("finance-center", "recommended"),
      f("device-management", "recommended"),
      f("members", "recommended"),
      f("waitlist", "recommended"),
      f("reports-finance", "recommended"),
      f("team", "recommended"),
      f("gift-cards", "optional"),
      f("inventory-ordering", "advanced"),
    ],
  },
  {
    id: "casual-dining",
    title: "休闲餐饮",
    titleEn: "Casual dining",
    version: 1,
    taxonomy: { group: "service-mode", sortOrder: 2 },
    features: [
      f("store-mgmt", "core"),
      f("dashboard", "core"),
      f("product-center-main", "core"),
      f("transactions", "core"),
      f("orders", "recommended"),
      f("kitchen-kds", "recommended"),
      f("queue-call", "recommended"),
      f("members", "recommended"),
      f("team", "recommended"),
      f("reports-finance", "recommended"),
      f("finance-center", "recommended"),
      f("print-templates", "recommended"),
      f("reservations", "optional"),
      f("gift-cards", "optional"),
      f("device-management", "recommended"),
    ],
  },
  {
    id: "delivery-first",
    title: "外卖专营",
    titleEn: "Delivery-first",
    version: 1,
    taxonomy: { group: "service-mode", sortOrder: 3 },
    features: [
      f("store-mgmt", "core"),
      f("dashboard", "core"),
      f("product-center-main", "core"),
      f("transactions", "core"),
      f("orders", "recommended"),
      f("kitchen-kds", "recommended"),
      f("members", "recommended"),
      f("team", "recommended"),
      f("reports-finance", "recommended"),
      f("device-management", "recommended"),
      f("print-templates", "recommended"),
      f("marketing", "optional"),
      f("inventory-ordering", "optional"),
    ],
  },
  {
    id: "general",
    title: "全功能 / 不确定",
    titleEn: "Full platform / not sure",
    version: 1,
    taxonomy: { group: "service-mode", sortOrder: 99 },
    features: [
      f("brand-mgmt", "core"),
      f("store-mgmt", "core"),
      f("dashboard", "core"),
      f("product-center-main", "core"),
      f("transactions", "core"),
      f("permission-mgmt", "core"),
      f("settings", "core"),
      f("team", "recommended"),
      f("orders", "recommended"),
      f("waitlist", "recommended"),
      f("marketing", "recommended"),
      f("promotions", "recommended"),
      f("members", "recommended"),
      f("gift-cards", "recommended"),
      f("reviews", "recommended"),
      f("queue-call", "recommended"),
      f("kitchen-kds", "recommended"),
      f("reservations", "recommended"),
      f("reports-finance", "recommended"),
      f("finance-center", "recommended"),
      f("print-templates", "recommended"),
      f("notifications", "recommended"),
      f("inventory-ordering", "recommended"),
      f("device-management", "recommended"),
      f("capital-turnover", "optional"),
      f("asset-center", "optional"),
      f("log-management", "optional"),
    ],
  },
  {
    id: "tea-drink",
    title: "茶饮",
    titleEn: "Tea & beverages",
    version: 1,
    taxonomy: { group: "cuisine", sortOrder: 1 },
    features: [
      f("store-mgmt", "core"),
      f("dashboard", "core"),
      f("product-center-main", "core"),
      f("transactions", "core"),
      f("team", "recommended"),
      f("members", "recommended"),
      f("queue-call", "recommended"),
      f("reports-finance", "recommended"),
      f("marketing", "optional"),
      f("promotions", "optional"),
    ],
  },
  {
    id: "coffee",
    title: "咖啡",
    titleEn: "Coffee shop",
    version: 1,
    taxonomy: { group: "cuisine", sortOrder: 2 },
    features: [
      f("store-mgmt", "core"),
      f("dashboard", "core"),
      f("product-center-main", "core"),
      f("transactions", "core"),
      f("team", "recommended"),
      f("members", "recommended"),
      f("queue-call", "recommended"),
      f("reports-finance", "recommended"),
      f("marketing", "optional"),
      f("promotions", "optional"),
    ],
  },
  {
    id: "bakery",
    title: "烘焙",
    titleEn: "Bakery",
    version: 1,
    taxonomy: { group: "cuisine", sortOrder: 3 },
    features: [
      f("store-mgmt", "core"),
      f("dashboard", "core"),
      f("product-center-main", "core"),
      f("transactions", "core"),
      f("waitlist", "recommended"),
      f("inventory-ordering", "recommended"),
      f("reports-finance", "recommended"),
      f("team", "recommended"),
    ],
  },
  {
    id: "hotpot",
    title: "火锅",
    titleEn: "Hot pot",
    version: 1,
    taxonomy: { group: "cuisine", sortOrder: 4 },
    features: [
      f("store-mgmt", "core"),
      f("dashboard", "core"),
      f("product-center-main", "core"),
      f("transactions", "core"),
      f("queue-call", "recommended"),
      f("reservations", "recommended"),
      f("kitchen-kds", "recommended"),
      f("orders", "recommended"),
      f("print-templates", "recommended"),
      f("finance-center", "recommended"),
      f("reports-finance", "recommended"),
      f("team", "recommended"),
    ],
  },
  {
    id: "bbq",
    title: "烧烤",
    titleEn: "BBQ & grill",
    version: 1,
    taxonomy: { group: "cuisine", sortOrder: 5 },
    features: [
      f("store-mgmt", "core"),
      f("dashboard", "core"),
      f("product-center-main", "core"),
      f("transactions", "core"),
      f("queue-call", "recommended"),
      f("reservations", "recommended"),
      f("kitchen-kds", "recommended"),
      f("orders", "recommended"),
      f("print-templates", "recommended"),
      f("finance-center", "recommended"),
      f("reports-finance", "recommended"),
      f("team", "recommended"),
    ],
  },
  {
    id: "buffet",
    title: "自助餐",
    titleEn: "Buffet",
    version: 1,
    taxonomy: { group: "cuisine", sortOrder: 6 },
    features: [
      f("store-mgmt", "core"),
      f("dashboard", "core"),
      f("product-center-main", "core"),
      f("transactions", "core"),
      f("queue-call", "recommended"),
      f("reservations", "recommended"),
      f("orders", "recommended"),
      f("kitchen-kds", "recommended"),
      f("finance-center", "recommended"),
      f("print-templates", "recommended"),
      f("members", "recommended"),
      f("team", "recommended"),
      f("reports-finance", "recommended"),
      f("device-management", "recommended"),
    ],
  },
  {
    id: "bar",
    title: "酒吧",
    titleEn: "Bar & pub",
    version: 1,
    taxonomy: { group: "cuisine", sortOrder: 7 },
    features: [
      f("store-mgmt", "core"),
      f("dashboard", "core"),
      f("product-center-main", "core"),
      f("transactions", "core"),
      f("orders", "recommended"),
      f("queue-call", "recommended"),
      f("finance-center", "recommended"),
      f("print-templates", "recommended"),
      f("members", "recommended"),
      f("team", "recommended"),
      f("reports-finance", "recommended"),
      f("promotions", "optional"),
      f("gift-cards", "optional"),
      f("device-management", "recommended"),
    ],
  },
  {
    id: "chinese-cuisine",
    title: "中餐",
    titleEn: "Chinese cuisine",
    version: 1,
    taxonomy: { group: "cuisine", sortOrder: 8 },
    features: [
      f("store-mgmt", "core"),
      f("dashboard", "core"),
      f("product-center-main", "core"),
      f("transactions", "core"),
      f("queue-call", "recommended"),
      f("reservations", "recommended"),
      f("orders", "recommended"),
      f("kitchen-kds", "recommended"),
      f("finance-center", "recommended"),
      f("print-templates", "recommended"),
      f("members", "recommended"),
      f("gift-cards", "optional"),
      f("team", "recommended"),
      f("reports-finance", "recommended"),
      f("device-management", "recommended"),
    ],
  },
  {
    id: "western-cuisine",
    title: "西餐",
    titleEn: "Western cuisine",
    version: 1,
    taxonomy: { group: "cuisine", sortOrder: 9 },
    features: [
      f("store-mgmt", "core"),
      f("dashboard", "core"),
      f("product-center-main", "core"),
      f("transactions", "core"),
      f("queue-call", "recommended"),
      f("reservations", "recommended"),
      f("orders", "recommended"),
      f("kitchen-kds", "recommended"),
      f("finance-center", "recommended"),
      f("print-templates", "recommended"),
      f("members", "recommended"),
      f("gift-cards", "optional"),
      f("team", "recommended"),
      f("reports-finance", "recommended"),
      f("device-management", "recommended"),
    ],
  },
  {
    id: "japanese-korean",
    title: "日韩料理",
    titleEn: "Japanese & Korean",
    version: 1,
    taxonomy: { group: "cuisine", sortOrder: 10 },
    features: [
      f("store-mgmt", "core"),
      f("dashboard", "core"),
      f("product-center-main", "core"),
      f("transactions", "core"),
      f("queue-call", "recommended"),
      f("reservations", "recommended"),
      f("orders", "recommended"),
      f("kitchen-kds", "recommended"),
      f("finance-center", "recommended"),
      f("print-templates", "recommended"),
      f("members", "recommended"),
      f("gift-cards", "optional"),
      f("team", "recommended"),
      f("reports-finance", "recommended"),
      f("device-management", "recommended"),
    ],
  },
  {
    id: "full-service",
    title: "正餐",
    titleEn: "Full service",
    version: 1,
    taxonomy: { group: "cuisine", sortOrder: 11 },
    features: [
      f("store-mgmt", "core"),
      f("dashboard", "core"),
      f("product-center-main", "core"),
      f("transactions", "core"),
      f("queue-call", "recommended"),
      f("reservations", "recommended"),
      f("orders", "recommended"),
      f("kitchen-kds", "recommended"),
      f("finance-center", "recommended"),
      f("print-templates", "recommended"),
      f("members", "recommended"),
      f("gift-cards", "optional"),
      f("team", "recommended"),
      f("reports-finance", "recommended"),
      f("device-management", "recommended"),
    ],
  },
];

export { PRODUCT_LINE_KEYS } from "./feature-presets-line-templates";

export const PRODUCT_LINE_QUICK_BUNDLES: ProductLineQuickBundle[] = [
  {
    id: "quick-emenu",
    title: "我只用电子菜单",
    titleEn: "eMenu only",
    presetIds: ["emenu-only"],
  },
  {
    id: "quick-kiosk",
    title: "我只用自助点餐机",
    titleEn: "Kiosk only",
    presetIds: ["kiosk-only"],
  },
  {
    id: "quick-pos-full",
    title: "完整门店收银",
    titleEn: "Full in-store POS",
    presetIds: ["pos-suite", "kds"],
  },
  {
    id: "quick-sdi",
    title: "我只用 SDI",
    titleEn: "SDI only",
    presetIds: ["sdi-only"],
  },
  {
    id: "quick-pos-go",
    title: "我只用 POS GO",
    titleEn: "POS GO only",
    presetIds: ["pos-go-only"],
  },
  {
    id: "quick-online",
    title: "外卖 / 网订为主",
    titleEn: "Delivery & online first",
    presetIds: ["online-order"],
  },
];

export function getBusinessTypePreset(id: BusinessTypeTag): BusinessTypePreset | undefined {
  return BUSINESS_TYPE_PRESETS.find((p) => p.id === id);
}
