export const OrderStatus = {
  INITIAL: 'INITIAL',
  SERVED: 'SERVED',
  ORDERED: 'ORDERED',
  SUBMITTED: 'SUBMITTED',
  PARTIALLY_SUBMITTED: 'PARTIALLY_SUBMITTED',
  PRINTED: 'PRINTED',
  UNPAID: 'UNPAID',
  PAID: 'PAID',
  ALL: 'ALL',
  UNSEND: 'UNSEND',
  HASBILL: 'HASBILL',
  PARTIALLY_PAID: 'PARTIALLY_PAID',
  DELIVERED: 'DELIVERED',
  CLOSED: 'CLOSED',
  UNCLOSED: 'UNCLOSED',
  CANCELED: 'CANCELED',
  VOID_BY_SYSTEM: 'VOID_BY_SYSTEM',
  CANCELED_AFTER_SENT_TO_KITCHEN: 'CANCELED_AFTER_SENT_TO_KITCHEN',
}

export const OrderType = {
  DINE_IN: 'DINE_IN',
  SELF_DINE_IN: 'SELF_DINE_IN',
  TOGO: 'TOGO',
  PICKUP: 'PICKUP',
  DELIVERY: 'DELIVERY',
  ONLINE_PICKUP: 'ONLINE_PICKUP',
  ONLINE_DELIVERY: 'ONLINE_DELIVERY',
  ONLINE_TOGO: 'ONLINE_TOGO',
}

export const SWITCH_NEW_ORDER = 'SWITCH_NEW_ORDER'
