/** AUTO-GENERATED by scripts/generate-foh-line-scope-matrix.mjs — do not edit */

export type FohLineScopeSource = "ui-module" | "group-default" | "manual" | "store-wide";

export interface FohLineScopeEntry {
  groupKey: string;
  lines: string[];
  source: FohLineScopeSource;
  module?: string;
}

export const FOH_LINE_NAV_ORDER = [
  { id: "pos", label: "POS" },
  { id: "pos-go", label: "POS GO" },
  { id: "paypad", label: "PayPad" },
  { id: "kiosk", label: "Kiosk" },
  { id: "emenu", label: "eMenu" },
  { id: "sdi", label: "SDI" },
  { id: "online-order", label: "Online Order" },
  { id: "cds", label: "CDS" },
  { id: "store-wide", label: "全店通用" },
] as const;

export type FohLineNavId = (typeof FOH_LINE_NAV_ORDER)[number]["id"];

export const FOH_LINE_SCOPE_BY_SEQ: Record<number, FohLineScopeEntry> = {
  "75": {
    "groupKey": "foh-pos-shell",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "ui-module",
    "module": "module-settings-pos-session-security-ui.ts"
  },
  "91": {
    "groupKey": "foh-guest-kitchen-send",
    "lines": [
      "kiosk",
      "emenu",
      "sdi",
      "online-order"
    ],
    "source": "group-default"
  },
  "107": {
    "groupKey": "foh-table-start-flow",
    "lines": [
      "kiosk",
      "emenu",
      "pos",
      "pos-go",
      "paypad",
      "sdi"
    ],
    "source": "ui-module",
    "module": "module-settings-table-selection-page-ui.ts"
  },
  "110": {
    "groupKey": "foh-pos-buttons",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "group-default"
  },
  "111": {
    "groupKey": "foh-table-start-flow",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "group-default"
  },
  "113": {
    "groupKey": "foh-kitchen-send-timing",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "group-default"
  },
  "114": {
    "groupKey": "foh-kitchen-send-timing",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "group-default"
  },
  "118": {
    "groupKey": "foh-pos-menu-scope",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "ui-module",
    "module": "module-settings-pos-menu-scope-lines-ui.ts"
  },
  "120": {
    "groupKey": "foh-kitchen-send-timing",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "group-default"
  },
  "121": {
    "groupKey": "foh-pos-order-cart",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "group-default"
  },
  "122": {
    "groupKey": "foh-pos-order-cart",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "ui-module",
    "module": "module-settings-pos-order-cart-pos-lines-ui.ts"
  },
  "123": {
    "groupKey": "foh-kitchen-send-timing",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "group-default"
  },
  "125": {
    "groupKey": "foh-kitchen-send-timing",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "group-default"
  },
  "132": {
    "groupKey": "foh-pos-order-cart",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "ui-module",
    "module": "module-settings-order-display-seat-ui.ts"
  },
  "133": {
    "groupKey": "foh-pos-order-cart",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "group-default"
  },
  "135": {
    "groupKey": "foh-pos-order-cart",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "group-default"
  },
  "137": {
    "groupKey": "foh-pos-order-cart",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "group-default"
  },
  "138": {
    "groupKey": "foh-pos-combo-ordering",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "ui-module",
    "module": "module-settings-pos-order-cart-pos-lines-ui.ts"
  },
  "139": {
    "groupKey": "foh-pos-combo-ordering",
    "lines": [
      "pos",
      "pos-go",
      "paypad",
      "kiosk",
      "emenu",
      "sdi",
      "online-order"
    ],
    "source": "ui-module",
    "module": "module-settings-pos-combo-ordering-ui.ts"
  },
  "141": {
    "groupKey": "foh-kitchen-send-timing",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "ui-module",
    "module": "module-settings-kitchen-line-edit-ui.ts"
  },
  "145": {
    "groupKey": "foh-pos-combo-ordering",
    "lines": [
      "pos",
      "pos-go",
      "paypad",
      "kiosk",
      "emenu",
      "sdi",
      "online-order"
    ],
    "source": "ui-module",
    "module": "module-settings-pos-combo-ordering-ui.ts"
  },
  "148": {
    "groupKey": "foh-pos-menu-scope",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "ui-module",
    "module": "module-settings-pos-menu-scope-lines-ui.ts"
  },
  "151": {
    "groupKey": "foh-pos-find-order-list",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "ui-module",
    "module": "module-settings-pos-find-order-list-ui.ts"
  },
  "152": {
    "groupKey": "foh-pos-find-order-list",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "ui-module",
    "module": "module-settings-pos-find-order-list-ui.ts"
  },
  "153": {
    "groupKey": "foh-pos-find-order-list",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "ui-module",
    "module": "module-settings-pos-find-order-list-ui.ts"
  },
  "165": {
    "groupKey": "foh-pos-shell",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "ui-module",
    "module": "module-settings-default-main-screen-ui.ts"
  },
  "166": {
    "groupKey": "foh-pos-shell",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "ui-module",
    "module": "module-settings-pos-session-security-ui.ts"
  },
  "169": {
    "groupKey": "foh-table-clear-ops",
    "lines": [
      "emenu",
      "pos",
      "pos-go",
      "paypad",
      "sdi"
    ],
    "source": "ui-module",
    "module": "module-settings-post-payment-clear-table-ui.ts"
  },
  "174": {
    "groupKey": "foh-pos-menu-scope",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "group-default"
  },
  "175": {
    "groupKey": "foh-pos-shell",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "ui-module",
    "module": "module-settings-pos-session-security-ui.ts"
  },
  "176": {
    "groupKey": "foh-pos-menu-scope",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "ui-module",
    "module": "module-settings-pos-menu-scope-lines-ui.ts"
  },
  "177": {
    "groupKey": "foh-pos-menu-scope",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "ui-module",
    "module": "module-settings-pos-menu-scope-lines-ui.ts"
  },
  "178": {
    "groupKey": "foh-pos-order-cart",
    "lines": [
      "pos",
      "pos-go",
      "paypad",
      "kiosk",
      "sdi",
      "online-order",
      "emenu"
    ],
    "source": "ui-module",
    "module": "module-settings-dish-sequence-id-display-ui.ts"
  },
  "193": {
    "groupKey": "foh-pos-buttons",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "group-default"
  },
  "194": {
    "groupKey": "foh-pos-buttons",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "group-default"
  },
  "195": {
    "groupKey": "foh-pos-buttons",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "group-default"
  },
  "196": {
    "groupKey": "foh-pos-buttons",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "group-default"
  },
  "197": {
    "groupKey": "foh-pos-buttons",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "group-default"
  },
  "198": {
    "groupKey": "foh-pos-buttons",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "group-default"
  },
  "199": {
    "groupKey": "foh-pos-buttons",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "group-default"
  },
  "200": {
    "groupKey": "foh-pos-buttons",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "group-default"
  },
  "201": {
    "groupKey": "foh-pos-buttons",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "group-default"
  },
  "202": {
    "groupKey": "foh-pos-buttons",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "group-default"
  },
  "203": {
    "groupKey": "foh-pos-buttons",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "group-default"
  },
  "204": {
    "groupKey": "foh-pos-buttons",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "group-default"
  },
  "205": {
    "groupKey": "foh-pos-buttons",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "group-default"
  },
  "206": {
    "groupKey": "foh-pos-buttons",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "group-default"
  },
  "207": {
    "groupKey": "foh-pos-buttons",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "group-default"
  },
  "208": {
    "groupKey": "foh-pos-buttons",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "group-default"
  },
  "209": {
    "groupKey": "foh-pos-buttons",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "group-default"
  },
  "210": {
    "groupKey": "foh-pos-buttons",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "group-default"
  },
  "211": {
    "groupKey": "foh-pos-buttons",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "group-default"
  },
  "212": {
    "groupKey": "foh-pos-buttons",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "group-default"
  },
  "213": {
    "groupKey": "foh-pos-buttons",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "group-default"
  },
  "214": {
    "groupKey": "foh-pos-buttons",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "group-default"
  },
  "215": {
    "groupKey": "foh-pos-buttons",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "group-default"
  },
  "216": {
    "groupKey": "foh-pos-menu-ui-layout",
    "lines": [
      "pos",
      "paypad"
    ],
    "source": "ui-module",
    "module": "module-settings-pos-menu-ui-layout-lines-ui.ts"
  },
  "217": {
    "groupKey": "foh-pos-menu-ui-layout",
    "lines": [
      "pos",
      "paypad"
    ],
    "source": "ui-module",
    "module": "module-settings-pos-menu-ui-layout-lines-ui.ts"
  },
  "218": {
    "groupKey": "foh-pos-menu-ui-layout",
    "lines": [
      "pos",
      "paypad"
    ],
    "source": "ui-module",
    "module": "module-settings-pos-menu-ui-layout-lines-ui.ts"
  },
  "219": {
    "groupKey": "foh-pos-menu-ui-layout",
    "lines": [
      "pos",
      "paypad"
    ],
    "source": "ui-module",
    "module": "module-settings-pos-menu-ui-layout-lines-ui.ts"
  },
  "220": {
    "groupKey": "foh-pos-menu-ui-layout",
    "lines": [
      "pos",
      "paypad"
    ],
    "source": "ui-module",
    "module": "module-settings-pos-menu-ui-layout-lines-ui.ts"
  },
  "221": {
    "groupKey": "foh-pos-checkout-entry",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "ui-module",
    "module": "module-settings-pos-checkout-entry-lines-ui.ts"
  },
  "222": {
    "groupKey": "foh-pos-order-cart",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "ui-module",
    "module": "module-settings-pos-order-cart-pos-lines-ui.ts"
  },
  "223": {
    "groupKey": "foh-pos-order-cart",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "ui-module",
    "module": "module-settings-pos-order-cart-pos-lines-ui.ts"
  },
  "248": {
    "groupKey": "foh-pos-checkout-entry",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "ui-module",
    "module": "module-settings-pos-checkout-entry-lines-ui.ts"
  },
  "251": {
    "groupKey": "foh-pos-find-order-list",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "ui-module",
    "module": "module-settings-pos-find-order-list-ui.ts"
  },
  "331": {
    "groupKey": "foh-pos-notification-control",
    "lines": [
      "store-wide"
    ],
    "source": "store-wide"
  },
  "332": {
    "groupKey": "foh-pos-notification-control",
    "lines": [
      "kiosk",
      "emenu",
      "pos",
      "pos-go",
      "paypad",
      "sdi",
      "online-order"
    ],
    "source": "ui-module",
    "module": "module-settings-notification-voice-alert-ui.ts"
  },
  "333": {
    "groupKey": "foh-tableside-service",
    "lines": [
      "store-wide"
    ],
    "source": "store-wide"
  },
  "345": {
    "groupKey": "foh-kitchen-send-timing",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "ui-module",
    "module": "module-settings-kitchen-send-password-auth-ui.ts"
  },
  "346": {
    "groupKey": "foh-pos-shell",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "ui-module",
    "module": "module-settings-home-password-auth-ui.ts"
  },
  "347": {
    "groupKey": "foh-table-clear-ops",
    "lines": [
      "emenu",
      "pos-go",
      "paypad"
    ],
    "source": "ui-module",
    "module": "module-settings-allow-change-server-ui.ts"
  },
  "348": {
    "groupKey": "foh-pos-menu-scope",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "ui-module",
    "module": "module-settings-pos-menu-scope-lines-ui.ts"
  },
  "349": {
    "groupKey": "foh-pos-shell",
    "lines": [
      "pos-go",
      "paypad"
    ],
    "source": "ui-module",
    "module": "module-settings-emenu-server-readonly-dish-ui.ts"
  },
  "350": {
    "groupKey": "foh-pos-menu-ui-layout",
    "lines": [
      "pos",
      "paypad"
    ],
    "source": "ui-module",
    "module": "module-settings-pos-menu-ui-layout-lines-ui.ts"
  },
  "351": {
    "groupKey": "foh-table-clear-ops",
    "lines": [
      "emenu",
      "pos-go",
      "paypad"
    ],
    "source": "ui-module",
    "module": "module-settings-clear-table-client-notification-ui.ts"
  },
  "443": {
    "groupKey": "foh-guest-duration-scenarios",
    "lines": [
      "store-wide"
    ],
    "source": "store-wide"
  },
  "483": {
    "groupKey": "foh-pos-buttons",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "group-default"
  },
  "484": {
    "groupKey": "foh-pos-buttons",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "group-default"
  },
  "485": {
    "groupKey": "foh-pos-buttons",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "group-default"
  },
  "486": {
    "groupKey": "foh-pos-buttons",
    "lines": [
      "pos",
      "pos-go",
      "paypad"
    ],
    "source": "group-default"
  },
  "487": {
    "groupKey": "foh-guest-order-type",
    "lines": [
      "kiosk",
      "emenu",
      "sdi",
      "online-order"
    ],
    "source": "group-default"
  },
  "488": {
    "groupKey": "foh-guest-order-type",
    "lines": [
      "kiosk",
      "emenu",
      "sdi",
      "online-order"
    ],
    "source": "group-default"
  },
  "489": {
    "groupKey": "foh-guest-order-type",
    "lines": [
      "kiosk",
      "emenu",
      "sdi",
      "online-order"
    ],
    "source": "group-default"
  },
  "490": {
    "groupKey": "foh-guest-order-type",
    "lines": [
      "kiosk",
      "emenu",
      "sdi",
      "online-order"
    ],
    "source": "group-default"
  },
  "491": {
    "groupKey": "foh-guest-order-type",
    "lines": [
      "kiosk",
      "emenu",
      "sdi",
      "online-order"
    ],
    "source": "group-default"
  },
  "502": {
    "groupKey": "foh-guest-kitchen-send",
    "lines": [
      "kiosk"
    ],
    "source": "manual"
  },
  "503": {
    "groupKey": "foh-guest-order-type",
    "lines": [
      "kiosk"
    ],
    "source": "ui-module",
    "module": "module-settings-table-delivery-meal-card-ui.ts"
  },
  "504": {
    "groupKey": "foh-guest-registration",
    "lines": [
      "kiosk"
    ],
    "source": "ui-module",
    "module": "module-settings-guest-phone-display-page-ui.ts"
  },
  "505": {
    "groupKey": "foh-guest-registration",
    "lines": [
      "kiosk"
    ],
    "source": "ui-module",
    "module": "module-settings-guest-phone-required-ui.ts"
  },
  "506": {
    "groupKey": "foh-guest-registration",
    "lines": [
      "kiosk",
      "emenu",
      "sdi",
      "online-order"
    ],
    "source": "group-default"
  },
  "507": {
    "groupKey": "foh-guest-registration",
    "lines": [
      "kiosk",
      "emenu",
      "sdi",
      "online-order"
    ],
    "source": "group-default"
  },
  "509": {
    "groupKey": "foh-guest-menu-body",
    "lines": [
      "kiosk",
      "emenu",
      "sdi",
      "online-order"
    ],
    "source": "group-default"
  },
  "510": {
    "groupKey": "foh-guest-registration",
    "lines": [
      "kiosk",
      "emenu",
      "sdi",
      "online-order",
      "cds"
    ],
    "source": "ui-module",
    "module": "module-settings-member-registration-fields-ui.ts"
  },
  "515": {
    "groupKey": "foh-guest-menu-body",
    "lines": [
      "kiosk",
      "emenu",
      "sdi",
      "online-order"
    ],
    "source": "ui-module",
    "module": "module-settings-guest-menu-structure-ui.ts"
  },
  "516": {
    "groupKey": "foh-guest-menu-body",
    "lines": [
      "kiosk",
      "emenu",
      "sdi",
      "online-order"
    ],
    "source": "ui-module",
    "module": "module-settings-guest-menu-structure-ui.ts"
  },
  "517": {
    "groupKey": "foh-guest-menu-body",
    "lines": [
      "kiosk",
      "emenu",
      "sdi",
      "online-order"
    ],
    "source": "ui-module",
    "module": "module-settings-guest-menu-structure-ui.ts"
  },
  "518": {
    "groupKey": "foh-guest-menu-body",
    "lines": [
      "kiosk",
      "emenu",
      "sdi",
      "online-order"
    ],
    "source": "ui-module",
    "module": "module-settings-guest-menu-structure-ui.ts"
  },
  "519": {
    "groupKey": "foh-guest-menu-body",
    "lines": [
      "kiosk",
      "emenu",
      "sdi",
      "online-order"
    ],
    "source": "ui-module",
    "module": "module-settings-guest-menu-structure-ui.ts"
  },
  "520": {
    "groupKey": "foh-guest-menu-body",
    "lines": [
      "kiosk",
      "emenu",
      "sdi",
      "online-order"
    ],
    "source": "ui-module",
    "module": "module-settings-guest-menu-structure-ui.ts"
  },
  "521": {
    "groupKey": "foh-tableside-service",
    "lines": [
      "kiosk",
      "emenu",
      "sdi",
      "online-order"
    ],
    "source": "ui-module",
    "module": "module-settings-order-remark-lines-ui.ts"
  },
  "522": {
    "groupKey": "foh-tableside-service",
    "lines": [
      "kiosk",
      "emenu",
      "sdi",
      "online-order"
    ],
    "source": "group-default"
  },
  "523": {
    "groupKey": "foh-tableside-service",
    "lines": [
      "kiosk",
      "emenu",
      "sdi",
      "online-order"
    ],
    "source": "group-default"
  },
  "524": {
    "groupKey": "foh-guest-menu-body",
    "lines": [
      "kiosk",
      "emenu",
      "sdi",
      "online-order"
    ],
    "source": "ui-module",
    "module": "module-settings-guest-menu-structure-ui.ts"
  },
  "525": {
    "groupKey": "foh-guest-menu-body",
    "lines": [
      "kiosk",
      "emenu",
      "sdi",
      "online-order"
    ],
    "source": "group-default"
  },
  "526": {
    "groupKey": "foh-guest-menu-body",
    "lines": [
      "kiosk",
      "emenu",
      "sdi",
      "online-order"
    ],
    "source": "group-default"
  },
  "528": {
    "groupKey": "foh-guest-menu-body",
    "lines": [
      "kiosk",
      "emenu",
      "sdi",
      "online-order"
    ],
    "source": "ui-module",
    "module": "module-settings-guest-menu-structure-ui.ts"
  },
  "532": {
    "groupKey": "foh-guest-menu-home",
    "lines": [
      "kiosk",
      "emenu"
    ],
    "source": "ui-module",
    "module": "module-settings-menusifu-brand-logo-ui.ts"
  },
  "534": {
    "groupKey": "foh-table-clear-ops",
    "lines": [
      "emenu",
      "kiosk",
      "pos",
      "pos-go",
      "paypad",
      "sdi"
    ],
    "source": "ui-module",
    "module": "module-settings-auto-clear-table-ui.ts"
  },
  "535": {
    "groupKey": "foh-wait-time-display",
    "lines": [
      "kiosk"
    ],
    "source": "ui-module",
    "module": "module-settings-wait-time-display-ui.ts"
  },
  "536": {
    "groupKey": "foh-wait-time-display",
    "lines": [
      "kiosk"
    ],
    "source": "ui-module",
    "module": "module-settings-wait-time-display-ui.ts"
  },
  "537": {
    "groupKey": "foh-wait-time-display",
    "lines": [
      "kiosk"
    ],
    "source": "ui-module",
    "module": "module-settings-wait-time-display-ui.ts"
  },
  "538": {
    "groupKey": "foh-wait-time-display",
    "lines": [
      "kiosk"
    ],
    "source": "ui-module",
    "module": "module-settings-wait-time-display-ui.ts"
  },
  "539": {
    "groupKey": "foh-wait-time-display",
    "lines": [
      "kiosk"
    ],
    "source": "ui-module",
    "module": "module-settings-wait-time-display-ui.ts"
  },
  "540": {
    "groupKey": "foh-wait-time-display",
    "lines": [
      "kiosk"
    ],
    "source": "ui-module",
    "module": "module-settings-wait-time-display-ui.ts"
  },
  "567": {
    "groupKey": "foh-guest-kitchen-send",
    "lines": [
      "kiosk",
      "emenu",
      "sdi",
      "online-order"
    ],
    "source": "group-default"
  },
  "569": {
    "groupKey": "foh-guest-pre-order",
    "lines": [
      "kiosk",
      "emenu",
      "sdi",
      "online-order"
    ],
    "source": "ui-module",
    "module": "module-settings-guest-order-notice-ui.ts"
  },
  "570": {
    "groupKey": "foh-guest-hotpot",
    "lines": [
      "emenu",
      "sdi"
    ],
    "source": "ui-module",
    "module": "module-settings-nested-ui.ts"
  },
  "571": {
    "groupKey": "foh-guest-duration-scenarios",
    "lines": [
      "emenu",
      "sdi"
    ],
    "source": "ui-module",
    "module": "module-settings-guest-category-mode-ui.ts"
  },
  "572": {
    "groupKey": "foh-guest-hotpot",
    "lines": [
      "emenu",
      "sdi"
    ],
    "source": "ui-module",
    "module": "module-settings-hotpot-base-required-ui.ts"
  },
  "573": {
    "groupKey": "foh-guest-hotpot",
    "lines": [
      "emenu",
      "sdi"
    ],
    "source": "ui-module",
    "module": "module-settings-hotpot-base-still-show-ui.ts"
  },
  "574": {
    "groupKey": "foh-guest-hotpot",
    "lines": [
      "emenu",
      "sdi"
    ],
    "source": "ui-module",
    "module": "module-settings-hotpot-base-order-mode-ui.ts"
  },
  "575": {
    "groupKey": "foh-guest-hotpot",
    "lines": [
      "emenu",
      "sdi"
    ],
    "source": "ui-module",
    "module": "module-settings-hotpot-half-surcharge-ui.ts"
  },
  "577": {
    "groupKey": "foh-guest-duration-scenarios",
    "lines": [
      "emenu"
    ],
    "source": "ui-module",
    "module": "module-settings-guest-dining-duration-ui.ts"
  },
  "578": {
    "groupKey": "foh-guest-duration-scenarios",
    "lines": [
      "emenu"
    ],
    "source": "ui-module",
    "module": "module-settings-guest-dining-duration-ui.ts"
  },
  "579": {
    "groupKey": "foh-guest-duration-scenarios",
    "lines": [
      "emenu"
    ],
    "source": "ui-module",
    "module": "module-settings-guest-dining-duration-ui.ts"
  },
  "580": {
    "groupKey": "foh-guest-duration-scenarios",
    "lines": [
      "emenu"
    ],
    "source": "ui-module",
    "module": "module-settings-guest-dining-duration-ui.ts"
  },
  "581": {
    "groupKey": "foh-guest-kitchen-send",
    "lines": [
      "kiosk",
      "emenu",
      "sdi",
      "online-order"
    ],
    "source": "group-default"
  },
  "592": {
    "groupKey": "foh-table-start-flow",
    "lines": [
      "kiosk",
      "emenu",
      "sdi",
      "online-order"
    ],
    "source": "group-default"
  },
  "599": {
    "groupKey": "foh-guest-menu-home",
    "lines": [
      "emenu",
      "sdi"
    ],
    "source": "ui-module",
    "module": "module-settings-guest-menu-group-by-line-ui.ts"
  },
  "600": {
    "groupKey": "foh-guest-menu-home",
    "lines": [
      "emenu",
      "sdi"
    ],
    "source": "ui-module",
    "module": "module-settings-guest-menu-line-toggle-ui.ts"
  },
  "601": {
    "groupKey": "foh-guest-menu-home",
    "lines": [
      "emenu",
      "sdi"
    ],
    "source": "ui-module",
    "module": "module-settings-guest-category-mode-ui.ts"
  },
  "602": {
    "groupKey": "foh-guest-menu-home",
    "lines": [
      "emenu",
      "sdi"
    ],
    "source": "ui-module",
    "module": "module-settings-guest-menu-classification-mode-ui.ts"
  },
  "604": {
    "groupKey": "foh-guest-menu-home",
    "lines": [
      "emenu"
    ],
    "source": "ui-module",
    "module": "module-settings-guest-emenu-pro-mode-ui.ts"
  },
  "606": {
    "groupKey": "foh-guest-menu-body",
    "lines": [
      "kiosk",
      "emenu",
      "sdi",
      "online-order"
    ],
    "source": "ui-module",
    "module": "module-settings-guest-menu-class-name-display-ui.ts"
  },
  "607": {
    "groupKey": "foh-guest-menu-body",
    "lines": [
      "emenu",
      "sdi",
      "kiosk"
    ],
    "source": "ui-module",
    "module": "module-settings-guest-menu-image-mode-ui.ts"
  },
  "608": {
    "groupKey": "foh-guest-menu-body",
    "lines": [
      "emenu",
      "sdi",
      "kiosk",
      "online-order"
    ],
    "source": "ui-module",
    "module": "module-settings-guest-dish-detail-display-ui.ts"
  },
  "611": {
    "groupKey": "foh-guest-menu-home",
    "lines": [
      "kiosk",
      "emenu",
      "sdi",
      "online-order"
    ],
    "source": "group-default"
  },
  "616": {
    "groupKey": "foh-guest-menu-body",
    "lines": [
      "emenu",
      "sdi"
    ],
    "source": "ui-module",
    "module": "module-settings-guest-menu-cart-ui.ts"
  },
  "617": {
    "groupKey": "foh-guest-menu-body",
    "lines": [
      "emenu",
      "sdi"
    ],
    "source": "ui-module",
    "module": "module-settings-guest-menu-cart-ui.ts"
  },
  "618": {
    "groupKey": "foh-guest-menu-body",
    "lines": [
      "emenu",
      "sdi"
    ],
    "source": "ui-module",
    "module": "module-settings-guest-menu-cart-ui.ts"
  },
  "619": {
    "groupKey": "foh-table-start-flow",
    "lines": [
      "kiosk",
      "emenu",
      "pos",
      "pos-go",
      "paypad",
      "sdi"
    ],
    "source": "ui-module",
    "module": "module-settings-party-size-selection-page-ui.ts"
  },
  "620": {
    "groupKey": "foh-guest-pre-order",
    "lines": [
      "kiosk",
      "emenu",
      "sdi",
      "online-order"
    ],
    "source": "group-default"
  },
  "621": {
    "groupKey": "foh-table-start-flow",
    "lines": [
      "emenu",
      "sdi"
    ],
    "source": "ui-module",
    "module": "module-settings-guest-change-party-size-ui.ts"
  },
  "622": {
    "groupKey": "foh-guest-registration",
    "lines": [
      "kiosk",
      "emenu",
      "cds",
      "sdi",
      "online-order"
    ],
    "source": "ui-module",
    "module": "module-settings-member-sms-verification-ui.ts"
  },
  "623": {
    "groupKey": "foh-guest-registration",
    "lines": [
      "kiosk",
      "emenu",
      "sdi",
      "online-order"
    ],
    "source": "ui-module",
    "module": "module-settings-member-login-policy-ui.ts"
  },
  "625": {
    "groupKey": "foh-table-start-flow",
    "lines": [
      "emenu",
      "sdi"
    ],
    "source": "ui-module",
    "module": "module-settings-child-excluded-from-order-limit-ui.ts"
  },
  "626": {
    "groupKey": "foh-guest-pre-order",
    "lines": [
      "kiosk",
      "emenu",
      "sdi",
      "online-order"
    ],
    "source": "group-default"
  },
  "627": {
    "groupKey": "foh-guest-pre-order",
    "lines": [
      "emenu"
    ],
    "source": "ui-module",
    "module": "module-settings-guest-category-mode-ui.ts"
  },
  "629": {
    "groupKey": "foh-tableside-service",
    "lines": [
      "kiosk",
      "emenu",
      "sdi",
      "online-order"
    ],
    "source": "group-default"
  },
  "637": {
    "groupKey": "foh-pos-order-alerts",
    "lines": [
      "kiosk",
      "emenu",
      "sdi",
      "online-order"
    ],
    "source": "ui-module",
    "module": "module-settings-staff-order-alerts-ui.ts"
  },
  "638": {
    "groupKey": "foh-pos-order-alerts",
    "lines": [
      "kiosk",
      "emenu",
      "sdi",
      "online-order"
    ],
    "source": "ui-module",
    "module": "module-settings-staff-order-alerts-ui.ts"
  },
  "639": {
    "groupKey": "foh-pos-order-alerts",
    "lines": [
      "emenu",
      "sdi"
    ],
    "source": "ui-module",
    "module": "module-settings-staff-order-alerts-ui.ts"
  },
  "640": {
    "groupKey": "foh-tableside-service",
    "lines": [
      "kiosk",
      "emenu",
      "sdi",
      "online-order"
    ],
    "source": "group-default"
  },
  "641": {
    "groupKey": "foh-tableside-service",
    "lines": [
      "kiosk",
      "emenu",
      "sdi",
      "online-order"
    ],
    "source": "group-default"
  },
  "642": {
    "groupKey": "foh-table-clear-ops",
    "lines": [
      "emenu"
    ],
    "source": "ui-module",
    "module": "module-settings-clear-table-button-ui.ts"
  },
  "643": {
    "groupKey": "foh-table-start-flow",
    "lines": [
      "emenu"
    ],
    "source": "ui-module",
    "module": "module-settings-pre-order-table-change-ui.ts"
  },
  "644": {
    "groupKey": "foh-table-start-flow",
    "lines": [
      "emenu"
    ],
    "source": "ui-module",
    "module": "module-settings-pre-order-table-change-ui.ts"
  },
  "645": {
    "groupKey": "foh-guest-menu-body",
    "lines": [
      "kiosk",
      "emenu",
      "sdi"
    ],
    "source": "ui-module",
    "module": "module-settings-guest-menu-dish-name-font-ui.ts"
  },
  "652": {
    "groupKey": "foh-guest-facing-locale",
    "lines": [
      "kiosk",
      "emenu",
      "sdi",
      "cds"
    ],
    "source": "manual"
  },
  "653": {
    "groupKey": "foh-guest-facing-locale",
    "lines": [
      "kiosk",
      "emenu",
      "sdi",
      "cds"
    ],
    "source": "manual"
  },
  "673": {
    "groupKey": "foh-wait-time-display",
    "lines": [
      "store-wide"
    ],
    "source": "store-wide"
  }
};

export function fohSeqAppliesToLine(seq: number, lineId: string): boolean {
  const entry = FOH_LINE_SCOPE_BY_SEQ[seq];
  if (!entry) return false;
  if (entry.lines.includes("store-wide")) return lineId === "store-wide";
  return entry.lines.includes(lineId);
}

export function fohSeqsForLine(lineId: string): number[] {
  return Object.entries(FOH_LINE_SCOPE_BY_SEQ)
    .filter(([, v]) =>
      v.lines.includes("store-wide") ? lineId === "store-wide" : v.lines.includes(lineId),
    )
    .map(([seq]) => Number(seq))
    .sort((a, b) => a - b);
}

export function fohLineNavLabel(lineId: string): string {
  return FOH_LINE_NAV_ORDER.find((l) => l.id === lineId)?.label ?? lineId;
}
