export const FETCH_LANGUAGE = 'FETCH_LANGUAGE';
export const FETCH_MENUGROUP = 'FETCH_MENUGROUP';
export const COMBO_MENU = 'COMBO_MENU';
export const STANDARD_CATE_DISH = 'STANDARD_CATE_DISH';
export const SET_ALL_MENU = 'SET_ALL_MENU';
export const FETCH_MERCHANT_PROFILE = 'FETCH_MERCHANT_PROFILE';

export const CURRENT_CATEGORY = 'CURRENT_CATEGORY';
export const CURRENT_CATEGORY_LIST = 'CURRENT_CATEGORY_LIST';
export const CURRENT_SALE_ITEMS = 'CURRENT_SALE_ITEMS';
export const CURRENT_ITEM = 'CURRENT_ITEM';
export const CURRENT_LANGUAGE = 'CURRENT_LANGUAGE';
export const CURRENT_COMBO = 'CURRENT_COMBO';
export const RESET_CURRENT_COMBO = 'RESET_CURRENT_COMBO';
export const INIT_ORDER_SEQUENCE = 'INIT_ORDER_SEQUENCE';
export const SET_ORDER_SEQUENCE = 'SET_ORDER_SEQUENCE';
export const REMOVE_ITEM_FROM_ORDER = 'REMOVE_ITEM_FROM_ORDER';
export const REMOVE_ZERO_QTY_ITEMS = 'REMOVE_ZERO_QTY_ITEMS';
export const EDIT_ORDER = 'EDIT_ORDER';
export const RESET_ITEM_LIST = 'RESET_ITEM_LIST';
export const ORDER_SEQUENCE = 'ORDER_SEQUENCE';
export const ADD_TO_SECTION = 'ADD_TO_SECTION';
export const CHANGE_DEFAULT_DISH = 'CHANGE_DEFAULT_DISH';
export const EDIT_DEFAULT_DISH = 'EDIT_DEFAULT_DISH';
export const ORDER_TYPE = 'ORDER_TYPE';
export const REMOVE_FROM_SECTION = 'REMOVE_FROM_SECTION';
export const SAVE_ORDER_RESULT = 'SAVE_ORDER_RESULT';
export const RESET_ORDER = 'RESET_ORDER';
export const SET_ORDER_STATUS = 'SET_ORDER_STATUS';
export const SET_PAYMENT_ID = 'SET_PAYMENT_ID';
export const SET_ORDER_NOTES = 'SET_ORDER_NOTES';
export const SET_ORDER_CUSTOMER = 'SET_ORDER_CUSTOMER';
export const SET_PICKUP_TIME = 'SET_PICKUP_TIME';
export const EXPEND_FREELIST = 'EXPEND_FREELIST';

export const SET_ORIGINAL_ITEM_LIST = 'SET_ORIGINAL_ITEM_LIST';
export const SAVE_TIP_AMOUNT = 'SAVE_TIP_AMOUNT';

export const SET_ITEM_PRICE = 'SET_ITEM_PRICE';
export const ADD_COMBO_OPTION = 'ADD_COMBO_OPTION';
export const ADD_OPTION = 'ADD_OPTION';
export const ADD_COMBO_TO_ORDER = 'ADD_COMBO_TO_ORDER';
export const REMOVE_PROMOTION_DISCOUNT_ITEM = 'REMOVE_PROMOTION_DISCOUNT_ITEM';
export const RECOUNT_CURRENT_ORDER_LIST = 'RECOUNT_CURRENT_ORDER_LIST';
export const IS_ORDER_EDIT = 'IS_ORDER_EDIT';
export const DEFAULT_CURRENT_COMBO = 'DEFAULT_CURRENT_COMBO';
export const ADD_CAMPAIGN_ITEMS_TO_ORDER = 'ADD_CAMPAIGN_ITEMS_TO_ORDER';
export const REMOVE_REWARD_ITEM_FROM_ORDER = 'REMOVE_REWARD_ITEM_FROM_ORDER';
export const REMOVE_ITEM_REWARD_INFO = 'REMOVE_ITEM_REWARD_INFO';
export const REMOVE_LOCAL_PROMOTION_REWARD_INFO =
  'REMOVE_LOCAL_PROMOTION_REWARD_INFO';
export const REMOVE_MANUAL_SELECT_REWARD_ITEM =
  'REMOVE_MANUAL_SELECT_REWARD_ITEM';

export const SET_SYSTEM_CONFIG = 'SET_SYSTEM_CONFIG';
export const SET_TAX_INFO = 'SET_TAX_INFO';
export const SET_COMPANY_PROFILE = 'SET_COMPANY_PROFILE';

export const MENU_ITEM_LIST = 'MENU_ITEM_LIST';
export const ITEM_SIZE_LIST = 'ITEM_SIZE_LIST';

export const SEARCH_KEY_WORD = 'SEARCH_KEY_WORD';
export const TEMP_ITEM_LIST = 'TEMP_ITEM_LIST';
export const TEMP_CURRENT_CATEGORY = 'TEMP_CURRENT_CATEGORY';

export const SAVE_PAYMENT_TYPE = 'SAVE_PAYMENT_TYPE';
export const APPEND_PAYMENT_TYPE_TRAIL = 'APPEND_PAYMENT_TYPE_TRAIL';
export const CLEAR_PAYMENT_TYPE_TRAIL = 'CLEAR_PAYMENT_TYPE_TRAIL';
export const MARK_POST_PAYMENT_ACTION = 'MARK_POST_PAYMENT_ACTION';
export const CLEAR_POST_PAYMENT_ACTIONS = 'CLEAR_POST_PAYMENT_ACTIONS';

export const SIDENAVINDEX = 'SIDENAVINDEX';
export const SIDENAVLISTINFO = 'SIDENAVLISTINFO';
export const REMOVEDIYCOMBO = 'REMOVEDIYCOMBO';
export const REMOVEDIYOPTCOMBO = 'REMOVEDIYOPTCOMBO';
export const CLEARDIYCOMBO = 'CLEARDIYCOMBO';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const REPLACE_TO_ORDER = 'REPLACE_TO_ORDER';
export const REPLACEORREDUCEOLDCOMBO = 'REPLACEORREDUCEOLDCOMBO';
export const SETKEYBOARDTOGGLE = 'SETKEYBOARDTOGGLE';
export const SPLICE_ORDER = 'SPLICE_ORDER';
export const ADD_TO_SECTION_BYID = 'ADD_TO_SECTION_BYID';
export const REMOVE_ONE_OPTIONS = 'REMOVE_ONE_OPTIONS';
export const REMOVE_ONE_ITEMS = 'REMOVE_ONE_ITEMS';
export const SPLICE_ALL_ITEMS = 'SPLICE_ALL_ITEMS';
export const SPLICE_SINGLE_ITEMS = 'SPLICE_SINGLE_ITEMS';
export const SET_LANMODAL = 'SET_LANMODAL';
export const SET_LANMODALFN = 'SET_LANMODALFN';
export const SET_NETWORKTATUS = 'SET_NETWORKTATUS';
export const DELETEALLBYID = 'DELETEALLBYID';
export const SETEDITCOMBOQTY = 'SETEDITCOMBOQTY';
export const ALL_SET_SYSTEM_CONFIG = 'ALL_SET_SYSTEM_CONFIG';
export const SELF_CONFIG = 'SELF_CONFIG';
export const SPLICEORDERBYSOLDOUT = 'SPLICEORDERBYSOLDOUT';
export const SETISREORDERFLAG = 'SETISREORDERFLAG';
export const SETTABELSERVICETYPE = 'SETTABELSERVICETYPE';
export const SETKIOSKCONFIGUSERID = 'SETKIOSKCONFIGUSERID';
export const MOBY_DEVICE_LINK_STATUS = 'MOBY_DEVICE_LINK_STATUS';
export const MOBY_DEVICE_INFO = 'MOBY_DEVICE_INFO';
export const TRIPOS_PAY_READY = 'TRIPOS_PAY_READY';
export const TRIPOS_PAY_FINISH = 'TRIPOS_PAY_FINISH';
export const SYSTEM_LICENSE = 'SYSTEM_LICENSE';
export const SET_IMG = 'SET_IMG';
export const SET_LOGO = 'SET_LOGO';
export const SET_BANNER = 'SET_BANNER';
export const SET_SHOW_BANNER = 'SET_SHOW_BANNER';
export const SET_BANNERPRO = 'SET_BANNERPRO';
export const SET_SHOW_BANNERPRO = 'SET_SHOW_BANNERPRO';
export const SET_SHOW_LOGINGUIDEDIALOG = 'SET_SHOW_LOGINGUIDEDIALOG';
export const SET_SHOW_WAITING_TIME_MODAL = 'SET_SHOW_WAITING_TIME_MODAL';
export const SET_SCREENSAVER = 'SET_SCREENSAVER';
export const SET_TOGO_OPTION = 'SET_TOGO_OPTION';
export const CLEAR_TOGO_OPTION = 'CLEAR_TOGO_OPTION';
export const SETREQUIRECATEGORY = 'SETREQUIRECATEGORY';
export const SET_CARD_RESULT = 'SET_CARD_RESULT';
export const PP_WS = 'PP_WS';
export const ISMENUUPDATED = 'ISMENUUPDATED';
export const MAKINGCUPNUM = 'MAKINGCUPNUM';
export const SETCATEYPAGEDOMTOP = 'SETCATEYPAGEDOMTOP';
export const SETORDERPAGEDOMTOP = 'SETORDERPAGEDOMTOP';
export const MENULOAD = 'MENULOAD';
export const SELECTEDBRAND = 'SELECTEDBRAND';
export const BRANDMENU = 'BRANDMENU';
export const SAVESEARCHITEM = 'SAVESEARCHITEM';
export const SETVLISTSCROLLHEIGHT = 'SETVLISTSCROLLHEIGHT';
export const SETLOCATOR = 'SETLOCATOR';
export const SET_TABLE_ID = 'SET_TABLE_ID';
export const SET_NUM_OF_GUESTS = 'SET_NUM_OF_GUESTS';

export const IS_AUTHORIZATION_DISPLAY_NAME = 'IS_AUTHORIZATION_DISPLAY_NAME';
export const SET_CUSTOMER_NAME = 'SET_CUSTOMER_NAME';
export const CHANGE_CHECK_FOOTER_VISIBLE = 'CHANGE_CHECK_FOOTER_VISIBLE';
export const REMOVE_FREE_ITEM_IN_ORDER = 'REMOVE_FREE_ITEM_IN_ORDER';
/**
 * CRM 相关
 * */
export const IS_SHOW_LOGIN_BAR = 'IS_SHOW_LOGIN_BAR';
export const CRM_MEMBER_INFO = 'CRM_MEMBER_INFO';
export const CRM_EARN_RULE = 'CRM_EARN_RULE';
export const IS_NEW_MEMBER = 'IS_NEW_MEMBER';
export const LOGIN_TYPE = 'LOGIN_TYPE';
export const SET_CRM_AUTH_CODE_VERIFIED = 'SET_CRM_AUTH_CODE_VERIFIED';
export const SET_CRM_AUTH_CODE_VERIFIED_PHONE =
  'SET_CRM_AUTH_CODE_VERIFIED_PHONE';
export const CHANGE_FREE_ITEM = 'CHANGE_FREE_ITEM';
export const SET_TEMP_FREE_ITEM = 'SET_TEMP_FREE_ITEM';
export const SET_DISCOUNT = 'SET_DISCOUNT';
export const IGNORE_REWARD = 'IGNORE_REWARD';
export const CRM_REWARD_RULE = 'CRM_REWARD_RULE';
export const ONBOARD_GIFT_RULE = 'ONBOARD_GIFT_RULE';
export const FREE_ITEM_MENU_POSITION = 'FREE_ITEM_MENU_POSITION';
export const IS_MEMBER_ORDERED_BEFORE = 'IS_MEMBER_ORDERED_BEFORE';
export const SET_TEMP_CAMPAIGN = 'SET_TEMP_CAMPAIGN';
export const SET_SELECTED_SPECIAL_ITEM = 'SET_SELECTED_SPECIAL_ITEM';
// 折扣相关
export const DISCOUNT_LIST = 'DISCOUNT_LIST';
export const SET_ITEM_LIST = 'SET_ITEM_LIST';

// promotion 相关
export const SET_PROMOTION = 'SET_PROMOTION';
export const SET_BUY_GIFTS = 'SET_BUY_GIFTS';
export const SET_SATISFY_RULES = 'SET_SATISFY_RULES';
export const SET_BUY_GIFTS_RULES = 'SET_BUY_GIFTS_RULES';
export const SET_EXCHANGE_PURCHASE_RULES = 'SET_EXCHANGE_PURCHASE_RULES';
export const SET_BUY_DISCOUNT_RULES = 'SET_BUY_DISCOUNT_RULES';
export const SET_ORDER_DISCOUNT = 'SET_ORDER_DISCOUNT';
export const SET_PROMO_CODE = 'SET_PROMO_CODE';
export const RECORD_KIOSK_DISCOUNT_PROMOTION =
  'RECORD_KIOSK_DISCOUNT_PROMOTION';
// 促销中台
export const SET_CLOUD_PROMOTION_LIST = 'SET_CLOUD_PROMOTION_LIST';
export const SET_CLOUD_PROMOTION_METAS = 'SET_CLOUD_PROMOTION_METAS';
export const CHANGE_CLOUD_PROMOTION_STATUS = 'CHANGE_CLOUD_PROMOTION_STATUS';
export const SET_ITEM_MATCH_CLOUD_PROMOTION = 'SET_ITEM_MATCH_CLOUD_PROMOTION';
export const SET_ITEM_VALID_PROMOTION = 'SET_ITEM_VALID_PROMOTION';
export const CHANGE_CRM_PROMOTION_CONTRARY_INFO =
  'CHANGE_CRM_PROMOTION_CONTRARY_INFO';
export const SET_IS_PAUSE_AUTO_VALIDATE_PROMOTION =
  'SET_IS_PAUSE_AUTO_VALIDATE_PROMOTION';
/**
 * 云Promotion
 * */
export const SET_CLOUD_PROMOTION = 'SET_CLOUD_PROMOTION';
export const RESET_PROMOTION = 'RESET_PROMOTION';
export const CHANGE_SKIP_PROMOTION_CALCULATION_STATUS =
  'CHANGE_SKIP_PROMOTION_CALCULATION_STATUS';
export const CHANGE_CRM_PROMOTION_MUTUAL_STATUS =
  'CHANGE_CRM_PROMOTION_MUTUAL_STATUS';

/**
 * AD
 * */
export const SET_AD_OUTLET_INFO = 'SET_AD_OUTLET_INFO';
export const SET_MERCHANT_CAMPAIGN_LIST = 'SET_MERCHANT_CAMPAIGN_LIST';
export const SET_MEMBERSHIP = 'SET_MEMBERSHIP';
export const SET_LOYALTY = 'SET_LOYALTY';
export const SET_ITEM_VOUCHERS = 'SET_ITEM_VOUCHERS';
export const SET_DOLLAR_VALUE_VOUCHERS = 'SET_DOLLAR_VALUE_VOUCHERS';
export const SET_DOLLAR_PERCENTAGE_VOUCHERS = 'SET_DOLLAR_PERCENTAGE_VOUCHERS';
export const SET_COMMIT_ID = 'SET_COMMIT_ID';
export const SET_ORDER_REWARD_ID = 'SET_ORDER_REWARD_ID';
export const SET_THIRD_PARTY_COMMIT_ID = 'SET_THIRD_PARTY_COMMIT_ID';

/**
 * crm-integration
 * */
export const SET_CRM_INTEGRATION_REWARD = 'SET_CRM_INTEGRATION_REWARD';
export const SET_CRM_INTEGRATION_CUSTOMER_VOUCHERS =
  'SET_CRM_INTEGRATION_CUSTOMER_VOUCHERS';
export const SET_SDK_META_DATA = 'SET_SDK_META_DATA';
export const SET_CRM_CUSTOMER_INFO = 'SET_CRM_CUSTOMER_INFO';
export const SET_NEED_COMMIT = 'SET_NEED_COMMIT';
export const CHANGE_REWARD_MODAL_VISIBLE = 'CHANGE_REWARD_MODAL_VISIBLE';
export const SET_AESERT_LIST_STATUS = 'SET_AESERT_LIST_STATUS';
/**
 * Poster pro
 * */
export const SET_POSTER_DATA = 'SET_POSTER_DATA';
export const SET_CURRENT_BLOCK = 'SET_CURRENT_BLOCK';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const CHANGE_POSTER_STATUS = 'CHANGE_POSTER_STATUS';
export const SET_KIOSK_MENU_TREE = 'SET_KIOSK_MENU_TREE';
export const SET_ECARD_SETTINGS = 'SET_ECARD_SETTINGS';
export const SET_ECARD_QUICK_AMOUNTS = 'SET_ECARD_QUICK_AMOUNTS';
export const SET_ECARD_CLOUD_GIFT_CARD_ITEM = 'SET_ECARD_CLOUD_GIFT_CARD_ITEM';
export const SET_SELECTED_ECARD = 'SET_SELECTED_ECARD';
export const SET_AVAILABLE_ECARDS = 'SET_AVAILABLE_ECARDS';
export const SET_ECARD_LAST_QUERY = 'SET_ECARD_LAST_QUERY';
export const SET_ECARD_LOADING = 'SET_ECARD_LOADING';
export const SET_GIFT_CARD_PAYMENT_INFO = 'SET_GIFT_CARD_PAYMENT_INFO';
