import { isPitApiError } from "./pit-api-error";
import { pitApi, type PitApi } from "./pit-api";
import type { PitRole, PitUser } from "./pit-types";
import { createPitPageLifetime, escapePitHtml, formatPitDate, pitRoleLabel, renderPitBanner, showPitToast } from "./pit-ui";
import { bindPitAdminModalAccessibility, openPitAdminModal, pitAdminModalTrigger } from "./pit-admin-modal";

type UserApi = Pick<PitApi, "listUsers" | "createUser" | "updateUser" | "resetUserPassword" | "revokeUserSessions">;
const field = "mt-1.5 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm dark:border-slate-700 dark:bg-slate-950";

export function renderPitUserPage(input: { user: PitUser; items?: PitUser[]; loading?: boolean; error?: string }): string {
  if (input.user.role !== "admin") return `<section data-pit-user-page>${renderPitBanner("无权访问用户与权限。", "danger")}</section>`;
  return `<section data-pit-user-page data-pit-route-page class="mx-auto w-full max-w-6xl p-4 sm:p-6 lg:p-8"><div class="rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="flex flex-wrap items-end justify-between gap-4 border-b border-slate-200 p-5 dark:border-slate-800"><div><p class="font-mono text-[10px] uppercase tracking-[.22em] text-amber-700">Local access registry</p><h2 class="mt-2 text-2xl font-bold">用户与权限</h2><p class="mt-1 text-sm text-slate-500">密码只在创建或重置时输入，不读取、不回显、不持久化到页面。</p></div><button data-pit-user-create class="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-bold text-amber-300 dark:bg-amber-400 dark:text-slate-950">创建用户</button></div><div data-pit-user-content class="p-5">${input.error ? renderPitBanner(input.error, "danger") : input.loading ? `<p class="py-16 text-center text-sm text-slate-500">正在读取用户…</p>` : `<div class="overflow-x-auto"><table class="w-full min-w-[760px] text-left text-sm"><thead class="text-xs text-slate-500"><tr><th class="pb-3">用户</th><th>角色</th><th>状态</th><th>更新时间</th><th class="text-right">操作</th></tr></thead><tbody>${(input.items ?? []).map((item) => `<tr data-pit-user-id="${escapePitHtml(item.id)}" class="border-t border-slate-100 dark:border-slate-800"><td class="py-4"><p class="font-semibold">${escapePitHtml(item.displayName)}</p><p class="font-mono text-xs text-slate-500">${escapePitHtml(item.username)}</p></td><td><select data-pit-user-role aria-label="${escapePitHtml(item.displayName)} 的角色" class="rounded-lg border px-2 py-1.5 dark:bg-slate-950" ${item.id === input.user.id ? "disabled" : ""}>${(["admin", "editor", "viewer"] as PitRole[]).map((role) => `<option value="${role}" ${role === item.role ? "selected" : ""}>${pitRoleLabel(role)}</option>`).join("")}</select></td><td><span class="rounded-full px-2.5 py-1 text-xs font-bold ${item.active ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-500"}">${item.active ? "已启用" : "已停用"}</span></td><td class="text-xs text-slate-500">${formatPitDate(item.updatedAt)}</td><td><div class="flex justify-end gap-1"><button data-pit-user-toggle class="rounded-lg border px-2.5 py-1.5 text-xs" ${item.id === input.user.id ? "disabled title=\"不能停用当前账号\"" : ""}>${item.active ? "停用" : "启用"}</button><button data-pit-user-reset class="rounded-lg border px-2.5 py-1.5 text-xs">重置密码</button><button data-pit-user-revoke class="rounded-lg border px-2.5 py-1.5 text-xs">撤销会话</button></div></td></tr>`).join("")}</tbody></table></div>`}</div></div><div data-pit-user-dialog-host></div></section>`;
}

function passwordDialog(mode: "create" | "reset", user?: PitUser): string {
  const create = mode === "create";
  return `<div data-pit-user-dialog class="fixed inset-0 z-[130] grid place-items-center bg-slate-950/55 p-4"><form data-pit-user-form data-pit-user-form-mode="${mode}" data-pit-target-id="${escapePitHtml(user?.id ?? "")}" role="dialog" aria-modal="true" aria-labelledby="pit-user-form-title" class="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl dark:bg-slate-900"><h3 id="pit-user-form-title" class="text-lg font-bold">${create ? "创建本地用户" : `重置 ${escapePitHtml(user?.displayName)} 的密码`}</h3>${create ? `<label class="mt-5 block text-xs font-bold">用户名<input name="username" required autocomplete="off" class="${field}"></label><label class="mt-4 block text-xs font-bold">显示名称<input name="displayName" required class="${field}"></label><label class="mt-4 block text-xs font-bold">角色<select name="role" class="${field}"><option value="viewer">只读者</option><option value="editor">编辑者</option><option value="admin">管理员</option></select></label>` : ""}<label class="mt-4 block text-xs font-bold">临时密码<input name="password" type="password" required minlength="12" autocomplete="new-password" class="${field}"></label><p class="mt-2 text-xs leading-5 text-slate-500">提交后将清空输入。系统不会再次显示或返回密码。</p><p data-pit-user-form-error role="alert" class="mt-3 text-xs text-rose-600"></p><div class="mt-6 flex justify-end gap-2"><button type="button" data-pit-user-dialog-cancel class="rounded-xl border px-4 py-2">取消</button><button type="submit" class="rounded-xl bg-amber-400 px-4 py-2 font-bold text-slate-950">${create ? "创建并显示一次" : "重置并显示一次"}</button></div></form></div>`;
}

function oneTimePasswordDialog(password: string): string {
  return `<div data-pit-user-dialog data-pit-password-once class="fixed inset-0 z-[130] grid place-items-center bg-slate-950/55 p-4"><div role="dialog" aria-modal="true" aria-labelledby="pit-password-once-title" class="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl dark:bg-slate-900"><h3 id="pit-password-once-title" class="text-lg font-bold">临时密码仅显示这一次</h3><p class="mt-2 text-sm text-slate-500">关闭后将从页面内存清除，无法再次查看。</p><div class="mt-5 flex items-center gap-2"><code data-pit-one-time-password class="min-w-0 flex-1 select-all overflow-hidden rounded-xl bg-slate-950 px-4 py-3 text-ellipsis text-amber-300">${escapePitHtml(password)}</code><button data-pit-copy-password class="rounded-xl border px-3 py-3 text-sm font-bold">复制</button></div><div class="mt-6 flex justify-end"><button data-pit-user-dialog-cancel class="rounded-xl bg-slate-950 px-4 py-2 text-sm font-bold text-white">我已保存，关闭</button></div></div></div>`;
}

function confirmDialog(action: string, title: string, message: string): string { return `<div data-pit-user-dialog data-pit-user-confirm="${escapePitHtml(action)}" class="fixed inset-0 z-[130] grid place-items-center bg-slate-950/55 p-4"><div role="dialog" aria-modal="true" aria-labelledby="pit-user-confirm-title" class="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl dark:bg-slate-900"><h3 id="pit-user-confirm-title" class="text-lg font-bold">${escapePitHtml(title)}</h3><p class="mt-3 text-sm leading-6 text-slate-500">${escapePitHtml(message)}</p><div class="mt-6 flex justify-end gap-2"><button data-pit-user-dialog-cancel class="rounded-xl border px-4 py-2">取消</button><button data-pit-user-confirm-submit class="rounded-xl bg-rose-600 px-4 py-2 font-bold text-white">确认</button></div></div></div>`; }

export function bindPitUserPage(root: HTMLElement, currentUser: PitUser, api: UserApi = pitApi): void {
  let page = root.querySelector<HTMLElement>("[data-pit-user-page]"); if (!page || currentUser.role !== "admin") return; const lifetime = createPitPageLifetime(page); let items: PitUser[] = []; let generation = 0;
  bindPitAdminModalAccessibility(root, lifetime.signal);
  const active = (g?: number) => !lifetime.signal.aborted && page!.isConnected && (g === undefined || g === generation);
  const paint = (error?: string) => { if (!active()) return; const wrapper = document.createElement("div"); wrapper.innerHTML = renderPitUserPage({ user: currentUser, items, error }); const next = wrapper.firstElementChild; if (next) page!.replaceChildren(...Array.from(next.childNodes)); };
  const load = async () => { const g = ++generation; try { const result = await api.listUsers({ signal: lifetime.signal }); if (active(g)) { items = result.items; paint(); } } catch (e) { if (active(g) && (e as Error).name !== "AbortError") paint(isPitApiError(e) ? e.message : "读取用户失败"); } };
  const host = () => root.querySelector<HTMLElement>("[data-pit-user-dialog-host]");
  root.addEventListener("click", (event) => { const target = event.target as Element;
    if (target.closest("[data-pit-user-dialog-cancel]")) { const dialog = target.closest("[data-pit-user-dialog]"); dialog?.querySelector<HTMLElement>("[data-pit-one-time-password]")?.replaceChildren(); dialog?.remove(); return; }
    if (target.closest("[data-pit-user-create]")) { const h = host(); if (h) openPitAdminModal(h, passwordDialog("create"), target.closest<HTMLElement>("button")); return; }
    if (target.closest("[data-pit-copy-password]")) { const value = target.closest("[data-pit-user-dialog]")?.querySelector<HTMLElement>("[data-pit-one-time-password]")?.textContent ?? ""; void navigator.clipboard.writeText(value).then(() => showPitToast("临时密码已复制", "success")).catch(() => showPitToast("复制失败，请手动选择复制", "warning")); return; }
    const row = target.closest<HTMLElement>("[data-pit-user-id]"); const user = items.find((entry) => entry.id === row?.dataset.pitUserId); if (!user) return;
    if (target.closest("[data-pit-user-reset]")) { const h = host(); if (h) openPitAdminModal(h, passwordDialog("reset", user), target.closest<HTMLElement>("button")); return; }
    if (target.closest("[data-pit-user-toggle]")) { const h = host(); if (h) openPitAdminModal(h, confirmDialog(`toggle:${user.id}:${user.active ? "0" : "1"}`, user.active ? "停用用户" : "启用用户", user.active ? "停用会立即撤销该用户的全部登录会话。" : "启用后该用户可再次登录."), target.closest<HTMLElement>("button")); return; }
    if (target.closest("[data-pit-user-revoke]")) { const h = host(); if (h) openPitAdminModal(h, confirmDialog(`revoke:${user.id}`, "撤销全部会话", "该用户在所有电脑上的 PIT 登录将立即失效。"), target.closest<HTMLElement>("button")); return; }
  }, { signal: lifetime.signal });
  root.addEventListener("change", (event) => { const select = (event.target as Element).closest<HTMLSelectElement>("[data-pit-user-role]"); const row = select?.closest<HTMLElement>("[data-pit-user-id]"); const user = items.find((entry) => entry.id === row?.dataset.pitUserId); if (!select || !user) return; const previous = user.role; select.disabled = true; const g = ++generation; void api.updateUser(user.id, { role: select.value as PitRole }).then(() => { if (active(g)) void load(); }).catch((e) => { if (active(g)) { select.value = previous; select.disabled = false; showPitToast(isPitApiError(e) ? e.message : "角色更新失败", "danger"); } }); }, { signal: lifetime.signal });
  root.addEventListener("submit", (event) => { const form = event.target as HTMLFormElement; if (!form.matches("[data-pit-user-form]")) return; event.preventDefault(); const data = new FormData(form); const password = String(data.get("password") ?? ""); const mode = form.dataset.pitUserFormMode; const originalTrigger = pitAdminModalTrigger(form.closest("[data-pit-user-dialog]")); const g = ++generation; const request = mode === "create" ? api.createUser({ username: String(data.get("username") ?? ""), displayName: String(data.get("displayName") ?? ""), role: String(data.get("role")) as PitRole, password }) : api.resetUserPassword(form.dataset.pitTargetId ?? "", password); void request.then((result) => { if (!active(g)) return; form.reset(); if (mode === "create" && "user" in result) { items = [...items, result.user]; paint(); } else form.closest("[data-pit-user-dialog]")?.remove(); const h = host(); if (h) openPitAdminModal(h, oneTimePasswordDialog(password), originalTrigger); }).catch((e) => { if (!active(g)) return; const error = form.querySelector<HTMLElement>("[data-pit-user-form-error]"); if (error) error.textContent = isPitApiError(e) ? e.message : "操作失败"; }); }, { signal: lifetime.signal });
  root.addEventListener("click", (event) => { const button = (event.target as Element).closest<HTMLButtonElement>("[data-pit-user-confirm-submit]"); const dialog = button?.closest<HTMLElement>("[data-pit-user-confirm]"); if (!button || !dialog) return; const [kind, id, state] = (dialog.dataset.pitUserConfirm ?? "").split(":"); button.disabled = true; const g = ++generation; const request = kind === "toggle" ? api.updateUser(id, { active: state === "1" }) : api.revokeUserSessions(id); void request.then(() => { if (active(g)) { dialog.remove(); showPitToast(kind === "toggle" ? "用户状态已更新" : "全部会话已撤销", "success"); void load(); } }).catch((e) => { if (active(g)) { button.disabled = false; showPitToast(isPitApiError(e) ? e.message : "操作失败", "danger"); } }); }, { signal: lifetime.signal });
  root.addEventListener("keydown", (event) => { if (event.key === "Escape") root.querySelector<HTMLElement>("[data-pit-user-dialog]")?.querySelector<HTMLElement>("[data-pit-user-dialog-cancel]")?.click(); }, { signal: lifetime.signal }); void load();
}
