"""
Square 后台思维导图：英文 UI 词条 → 中文（餐饮商家后台语境）。
用于覆盖机器翻译中易错的短标签；长句仍以缓存中的机翻结果为主。
"""

from __future__ import annotations

# key 必须与 .mm 中 TEXT 完全一致（区分大小写）
PRE_GLOSSARY: dict[str, str] = {
    # 顶层 / 通用
    "Home": "首页",
    "Performance": "经营概览",
    "Locations": "门店列表",
    "Location": "门店",
    "Name": "名称",
    "Date": "日期",
    "Today": "今日",
    "Yesterday": "昨日",
    "This week": "本周",
    "Last week": "上周",
    "This month": "本月",
    "Last month": "上月",
    "This year": "本年",
    "Last year": "去年",
    "Custom": "自定义",
    "Prior to day": "对比：前一日",
    "Prior to Thursday": "对比：上周四",
    "4 weeks prior": "对比：前 4 周",
    "52 weeks prior": "对比：前 52 周",
    "Prior to year": "对比：去年同期",
    "Bills": "账单",
    "All": "全部",
    "Open": "进行中",
    "Closed": "已结账",
    "Net sales": "净销售额",
    "Gross sales": "总销售额",
    "Transactions": "交易笔数",
    "Average sale": "客单价",
    "Labour %": "人工成本占比",
    "Labour % of net sales": "人工成本占净销售额比例",
    "Comps & discounts": "免单与折扣",
    "Tips": "小费",
    "Items & menus": "商品与菜单",
    "Items": "商品",
    "Item": "商品",
    "Item library": "商品库",
    "GTIN": "商品条码（GTIN）",
    "SKU": "SKU（库存编码）",
    "Reporting category": "报表分类",
    "Channel listings": "渠道上架",
    "Service library": "服务库",
    "Sold by": "售卖方式",
    "Stock on hand": "现有库存",
    "Availability": "可售状态",
    "Status": "状态",
    "Price": "价格",
    "Weight": "重量",
    "Duration": "时长",
    "Image library": "图片库",
    "Resources": "资源",
    "Modifiers": "加料/规格（Modifier）",
    "Categories": "分类",
    "Discounts": "折扣",
    "Options": "选项",
    "Units": "单位",
    "Custom attributes": "自定义属性",
    "Settings": "设置",
    "Item defaults": "商品默认配置",
    "Item type": "商品类型",
    "Physical good": "实物商品",
    "Prepared food and beverage": "餐食与饮品（餐饮）",
    "Event": "活动/门票",
    "Digital": "数字商品",
    "Other": "其他",
    "Donation": "捐赠",
    "Channels": "渠道",
    "Site visibility": "站点可见性",
    "Visible": "可见",
    "Hidden": "隐藏",
    "Unavailable": "不可售",
    "Dining options": "就餐方式",
    "Option": "选项",
    "To Go": "打包带走",
    "Delivery": "外送",
    "Pick Up": "自提",
    "DineIn": "堂食",
    "Dineln": "堂食",
    "Default Dining Option": "默认就餐方式",
    "Edit Dining Options": "编辑就餐方式",
    "Comp and void": "免单与作废",
    "Comp Reasons": "免单原因",
    "Void Reasons": "作废原因",
    "Create Comp Reason": "新增免单原因",
    "Create Void Reason": "新增作废原因",
    "Inventory": "库存",
    "Applicable locations": "适用门店",
    "Edit applicable locations": "编辑适用门店",
    "Enable for all future locations": "对未来新增门店自动启用",
    "Payment links": "支付链接",
    "Choose purpose": "选择用途",
    "Take a payment": "收款",
    "Sell an item": "售卖商品",
    "Sell an event or class": "售卖活动/课程",
    "Accept a donation": "接受捐赠",
    "Menus": "菜单",
    "Create a menu": "创建菜单",
    "History": "历史记录",
    "Stock history": "库存历史",
    "Suppliers": "供应商",
    "Vendors": "供货商",
    "Ingredient tracking": "原料追踪",
    "Order guide": "订货指引",
    "Get started": "开始使用",
    "Select a plan": "选择方案",
    "Gift cards": "礼品卡",
    "Overview": "概览",
    "EGift cards": "电子礼品卡",
    "Configure": "配置",
    "Square Point of Sale app": "Square POS 收银应用",
    "Sell eGift cards in-store": "门店售卖电子礼品卡",
    "Online": "线上",
    "Sell eGift cards Online": "线上售卖电子礼品卡",
    "Allow bulk eGift card ordering": "允许批量购买电子礼品卡",
    "Discount Codes": "优惠码",
    "Create Code": "创建优惠码",
    "Create Discount": "创建折扣",
    "Discount Amount": "折扣金额",
    "Minimum Load": "最低充值金额",
    "Discount Code": "优惠码",
    "Active Designs": "启用的设计模板",
    "Manage Designs": "管理设计模板",
    # 机翻常见误译纠正（词条级）
    "Restaurant": "餐厅",
    "Kiosk": "自助点餐机",
    "Checkout": "结账",
    "Comps": "免单",
}

# 对缓存「译文」做子串级修正（不依赖英文 key）
ZH_VALUE_PATCHES: list[tuple[str, str]] = [
    ("补偿和无效", "免单与作废"),
    ("创造无效理由", "新增作废原因"),
    ("尖端", "小费"),
    ("风俗", "自定义"),
    ("项目和菜单", "商品与菜单"),
    ("体力好", "实物商品"),
    ("信息亭", "自助点餐机"),
    ("送货应用程序", "外卖应用"),
    ("在线订购网站", "线上点餐网站"),
    ("任何餐厅 POS 模式", "各类餐饮 POS 经营模式"),
    ("E礼品卡", "电子礼品卡"),
    ("主动设计", "启用的设计模板"),
    ("塑料礼品卡", "实体礼品卡"),
    ("存货", "库存"),
    ("地点", "门店"),
    ("位置", "门店"),
    ("适用地点", "适用门店"),
    ("所有地点", "所有门店"),
    ("编辑适用位置", "编辑适用门店"),
    ("为所有未来位置启用", "对未来新增门店自动启用"),
    ("销售活动或课程", "售卖活动/课程"),
    ("选择目的", "选择用途"),
    ("赠品和折扣", "免单与折扣"),
    ("销售总额", "总销售额"),
    ("劳动力占净销售额的百分比", "人工成本占净销售额比例"),
    ("劳动 ％", "人工成本占比"),
    ("平均销售额", "客单价"),
    ("姓名", "名称"),
    ("修饰符", "加料/规格（Modifier）"),
    ("频道列表", "渠道上架"),
    ("报告类别", "报表分类"),
    ("可用性", "可售状态"),
    ("地位", "状态"),
    ("期间", "时长"),
    ("项目库", "商品库"),
    ("项目默认值", "商品默认配置"),
    ("物品类型", "商品类型"),
    ("预制食品和饮料", "餐食与饮品（餐饮）"),
    ("物品", "商品"),
    ("表现", "经营概览"),
    ("Insert、Tap、Swipe", "插卡、挥卡、刷卡"),
    ("Payment Links、", "支付链接、"),
    ("Square for Retail", "Square 零售版"),
    ("Square Online", "Square 线上商城"),
    ("Square Restaurant POS", "Square 餐饮版 POS"),
    ("Invoices Plus", "发票增强版订阅"),
    ("Error 500 (Server Error)!!1500.That’s an error.There was an error. Please try again later.That’s all we know.", "服务器错误（500）：页面暂时无法加载，请稍后重试。"),
    ("DoorDash for Square 餐厅", "DoorDash 与 Square 餐饮对接"),
    ("按 Enter 键", "按回车键"),
]

# 整句覆盖：机翻产生「英文前缀 + 中文」拼接等明显问题时使用（key 与 .mm 中 TEXT 完全一致）
EXACT_OVERRIDES: dict[str, str] = {
    "Manage all your bills in one place. Pay with your Square checking account, bank account (coming soon), or credit card - and let your vendors choose how they get paid.": (
        "在一处集中管理账单。可使用 Square 支票账户、银行账户（即将推出）或信用卡付款，"
        "并由供应商自主选择收款方式。"
    ),
    "Square商家平台-后台结构-英文": "Square 商家平台：后台信息架构（中文）",
    # 机翻偶发返回错误页文案，按原英文节点人工恢复语义
    "Dashboard or mobile add-on links": "控制台或移动端扩展链接",
    "Marketing technology platform designed to make growing your restaurant easy.": "营销技术平台，帮助餐厅更轻松拓展经营。",
}


def apply_exact_overrides(cache: dict[str, str]) -> None:
    for k, v in EXACT_OVERRIDES.items():
        if k in cache:
            cache[k] = v
