/**
 * 打印中心 · 收据明细与价格（行项显隐与价格呈现，均为开关）。
 */

export const RECEIPT_PRINT_ZERO_PRICE_DISH_SEQ = 275;
export const RECEIPT_PRINT_ZERO_PRICE_SUBDISH_SEQ = 274;
export const RECEIPT_PRINT_ZERO_PRICE_MODIFIER_SEQ = 278;
export const RECEIPT_PRINT_MODIFIER_DISCOUNT_SURCHARGE_PRICE_SEQ = 276;
export const RECEIPT_SHOW_DISCOUNT_ORIGINAL_PRICE_SEQ = 285;
export const RECEIPT_PRINT_DISH_QUANTITY_SEQ = 289;
export const RECEIPT_SHOW_GUEST_NOTES_SEQ = 283;
export const RECEIPT_PRINT_KITCHEN_NAME_SEQ = 284;

/** 组内顺序与 settings-intra-group-sort 一致 */
export const RECEIPT_LINE_CONTENT_TOGGLE_SEQS: readonly number[] = [
  RECEIPT_PRINT_ZERO_PRICE_DISH_SEQ,
  RECEIPT_PRINT_ZERO_PRICE_SUBDISH_SEQ,
  RECEIPT_PRINT_ZERO_PRICE_MODIFIER_SEQ,
  RECEIPT_PRINT_MODIFIER_DISCOUNT_SURCHARGE_PRICE_SEQ,
  RECEIPT_SHOW_DISCOUNT_ORIGINAL_PRICE_SEQ,
  RECEIPT_PRINT_DISH_QUANTITY_SEQ,
  RECEIPT_SHOW_GUEST_NOTES_SEQ,
  RECEIPT_PRINT_KITCHEN_NAME_SEQ,
];

export function isReceiptLineContentToggleSeq(seq: number): boolean {
  return (RECEIPT_LINE_CONTENT_TOGGLE_SEQS as readonly number[]).includes(seq);
}
